ALTER TABLE pfmea.products ADD COLUMN IF NOT EXISTS dimensions VARCHAR;
ALTER TABLE pfmea.products ADD COLUMN IF NOT EXISTS weight DOUBLE PRECISION;
ALTER TABLE pfmea.products ADD COLUMN IF NOT EXISTS cycle_time DOUBLE PRECISION;
ALTER TABLE pfmea.products ADD COLUMN IF NOT EXISTS rate_per_hour DOUBLE PRECISION;
